media:
  input: src/assets/images
  output: /
content:
  - name: irasai
    label: Įrašai
    type: collection
    path: src/content/irasai
    view:
      fields: [ title, published ]
    filename: '{primary}.mdx'
    fields:
      - { name: title, label: Antraštė, type: string, required: true }
      - { name: published, label: Paskelbimo data, type: date, required: true }
      - { name: description, label: "Trumpas aprašymas (optional, tekstas po antrašte)", type: string }
      - { name: image, label: "Paveiksliukas (optional, LitMO logo by default)", type: string }
      - { name: updated, label: Redagavimo data (optional), type: date }
      - { name: body, label: Įrašo tekstas, type: text }